# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  minio:
    image: docker.io/bitnami/minio:2025
    environment:
      MINIO_BROWSER: "on"
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'

volumes:
  minio_data:
    driver: local
